### ISSUE TITLE
config文件参数不合理

### ISSUE THREAD

**Issue by Cheahom** [shiheyingzhe/Mask_face_recognitionZ#1]
config['epochs'] = 1900
config['num_train_triplets'] = 1000
这两项非常不合理呀，epochs开的太大了。。FaceNet本来用的是100000个三元组，这里就只剩1000个了。。

**Comment by ZouJiu1** [comment]
已经修改了的，验证集的AUC达到最大时就可以停止训练了不要过拟合，epoch数量已经修改，1000是对于clone里面的图片，这些图片很少，所以三元组数量少，下载全部图片数据以后，需要设置为100000

**Comment by Cheahom** [comment]
我在这里发完才想起来找怡铭要你的联系方式= =，按上次微信上说的改成100000之后已经能复现啦

**Comment by ZouJiu1** [comment]
好的

**Comment by ZouJiu1** [comment]
那就关闭这个话题了
